### ISSUE TITLE
大佬，建议您像qplayer一样能加个网易云音乐解析

### ISSUE THREAD

**Issue by misaka10843** [moeshin/QPlayer2#2]
大佬，您能不能加个网易云音乐解析呢？像QPlayer一样
大概的话就是讲QPlayer的IDExplain.php中的212行的
`$key = 'mp3';`
mp3改成audio然后在Plugin.php中引用就可以了（虽然无法获取歌词）
`$getMusic = new Typecho_Widget_Helper_Form_Element_Radio('getMusic',NULL,NULL,_t('添加网易云音乐(主机需支持curl扩展)'),_t('
        	<div style="background-color:#467b96;padding:5px 8px;max-width:110px;border-radius: 2px;"><a href="'.Helper::options()->pluginUrl.'/QPlayer/IDExplain.php" target="_blank" style="font-size:14px;color:#fff;outline:none;text-decoration:none;">网易云音乐id解析</a>
        	</div>请自行去网易云音乐网页版获取音乐id(具体在每个音乐项目的网址最后会有个id)。<b>将解析出的音乐链接复制到下面歌曲列表里(注意检查与现有歌曲是否用英文,隔开)</b>'));
        $form->addInput($getMusic);
`

**Comment by misaka10843** [comment]
并且在IDExplain.php的211行加入
`if ($key == 'title') {
                    $key = 'name';
                }`

**Comment by moeshin** [comment]
这个解析不是有点问题吗？最多只返回十首，而且没有音频链接

**Comment by moeshin** [comment]
https://github.com/moeshin/QPlayer2-Typecho

```
[{"server": "netease", "type": "playlist", "id": "3136952023"}]
```

> server：netease、tencent、baidu、xiami、kugou
> type：playlist、song、album、artist
> [网易云动态歌单整理](https://github.com/moeshin/netease-music-dynamic-playlist)

**Comment by misaka10843** [comment]
音频链接有啊？因为网易这几年改了他的音乐链接，要把解析的php中177行改成` 'location' => 'http://music.163.com/song/media/outer/url?id='.$data['id'].'.mp3',  `就可以了，至于一次只能返回十首....
可能是网易官方api的问题嘛
至少可以用嘛😂

**Comment by moeshin** [comment]
https://moeshin.github.io/QPlayer2/demos/netease.html
https://github.com/moeshin/QPlayer2/blob/master/demos/netease.php
